# Generated by Django 5.2.7 on 2025-10-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentbatchenrollment',
            options={'ordering': ['-enrollment_date']},
        ),
    ]
