# Generated by Django 5.2.7 on 2025-10-20 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_initial'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentBatchEnrollment',
            new_name='StudentEnrollment',
        ),
    ]
