# Generated by Django 5.2.7 on 2025-10-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_id',
        ),
    ]
