# Generated by Django 5.2.7 on 2025-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
