# Generated by Django 5.2.7 on 2025-10-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_batch_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-start_date'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveConstraint(
            model_name='batch',
            name='valid_date_range',
        ),
    ]
