# Generated by Django 5.2.7 on 2025-10-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_batch_valid_date_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='price',
        ),
    ]
