# Generated by Django 5.2.7 on 2025-10-15 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_SIGNUP', 'New Signup'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('BATCH_CREATED', 'Batch Created'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('SYSTEM', 'System')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('email_type', models.CharField(choices=[('VERIFICATION', 'Verification'), ('NEW_SIGNUP_ALERT', 'New Signup Alert'), ('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('ENROLLMENT_CONFIRMATION', 'Enrollment Confirmation'), ('GENERAL', 'General')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Queue',
                'verbose_name_plural': 'Email Queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_OVERDUE', 'Payment Overdue'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('PAYMENT_RECEIVED', 'Payment Received')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
