# Generated by Django 5.2.7 on 2025-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_OVERDUE', 'Payment Overdue'), ('STUDENT_ENROLLED', 'Student Enrolled')], max_length=50),
        ),
    ]
