# Generated by Django 5.2.7 on 2025-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_adminnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_SIGNUP', 'New Signup'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('BATCH_CREATED', 'Batch Created'), ('STUDENT_ENROLLED', 'Student Enrolled'), ('SYSTEM', 'System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_OVERDUE', 'Payment Overdue'), ('STUDENT_ENROLLED', 'Student Enrolled')], max_length=50),
        ),
    ]
